### ISSUE TITLE
Request: guidelines for translating developer_guide.md

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/kovri-docs#90]
The entire section "Code of Conduct (22/C4.1)" is pretty large and uses legalese to be precise and is sort of a license agreement.

Should this section be translated? And if so, could we make a note of it somewhere?

I have a feeling that in some projects, license-type documents (GPL et al) are not translated but left as-is. What is the kovri policy on this? In this repo, German and French have been translated.

**Comment by anonimal** [comment]
Pinging @fluffypony

**Comment by Josexv1** [comment]
Most of the times Licenses should be left intact IIRC... I don't translate them.

**Comment by rodolfo912** [comment]
I suggest to provide translations of licences or similar but to include a caveat that only the English original is official and valid. By doing so, there is value added for non-English speakers without possibly causing legal trouble.

Something similar to what GNU does (https://www.gnu.org/licenses/translations.en.html):

> This is an unofficial translation of the GNU General Public License into language. It was not published by the Free Software Foundation, and does not legally state the distribution terms for software that uses the GNU GPL—only the original English text of the GNU GPL does that. However, we hope that this translation will help language speakers understand the GNU GPL better.

**Comment by erciccione** [comment]
I think we shouldn't translate licenses. A misinterpretated translation could couse big legal problems (Monerujo's licenses are left unstranslated, for example)

**Comment by rodolfo912** [comment]
Just to elaborate on my abovementioned position. Saying "licences or similar" has been too vague, what I specifically had in mind was the Code of Conduct (22/C4.1). I think translations of this license offer value to (potential) Kovri users who might be interested in Kovri's development and collaboration process. Not so much to developers, the number of developers who, both, can contribute in a meaningful way and do not understand English, is probably zero.

This applies to Monerujo's license or other more legalese licenses to a far lesser degree (who reads them anyway?). Still, if someone wants to take the big effort of translating them and provide this information, I would not hinder them.

In any case, as stated above, a caveat should be added to prevent misinterpretation and legal trouble.

**Comment by ProkhorZ** [comment]
Hi, I'm working on Dutch translations. I'm translating everything in this repo, but I'm not sure whether the most technical content, like the Developer Guide itself, needs to be translated for all languages. Developers will probably speak English and use English terms. For me, translation is mostly a marketing tool: addressing people in the language they feel most comfortable with.

On the other hand, Pieter Hintjens' ZeroMQ Code of Conduct is the heart and soul of The Monero Project. It defines the open mentality that has enabled us to recruit more than 460 contributors by promising to merge their work. It's not a license, although the original title is Collective Code Construction Contract (C4). It's written in legalese by a developer, not a lawyer, apparently as a way to emphasize that norms for behavior are just as important as technical standards. I'm excited to translate the C4! Like explaining the FFS, why we don't have a premine or what the difference between a lead maintainer and a CEO is, demonstrating ethical behavior is not just for internal use, but also a propaganda tool. 

My proposal would be to move the Code of Conduct to a separate document. The current developer_guide.md is way too long for a web page. Then it would be easier to translate either the Developer Guide or the Code of Conduct. And getmonero.org could link to the Code of Conduct, or copy it.

The four sentences at the beginning referring to the GNU General Public License could be left in English, but they're often translated in FOSS documentation. You can search http://www.tausdata.org/ for examples. The name of the license must always be left in English, since only the English text of the license is valid.

The reference to RFC 2119 under Language is a special case, which I'll open a new issue for.

**Comment by ProkhorZ** [comment]
By the way, the text of the code of conduct refers to itself as C4, which isn't defined, because we don't use the title Collective Code Construction Contract (C4). And the version we use has been deprecated by ZeroMQ. [The new version](https://rfc.zeromq.org/spec:42/C4/) has numbered paragraphs, an abstract has been added at the beginning and there's some new language about deprecating names. That's all the difference I could see in a diff. [The history is here](https://github.com/zeromq/rfc/commits/master/42).

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-docs/issues/102 for details.
